## sudo apt install libdata-yaml-perl libyaml-perl
#ARDUINO_VARIANT = nodemcu
#INCLUDE_VARIANT = nodemcu
#ARDUINO_ARCH=esp8266
#SERIAL_PORT = /dev/ttyUSB0
#SKETCH = esp_small_relay.ino
#BOARD = nodemcu
#ARDUINO_LIBS += NTPClient ElegantOTA 
#include /BOARDS/ESP/Esp8266-Arduino-Makefile/espXArduino.mk

ARDUINO_VARIANT = nodemcu
SERIAL_PORT = /dev/ttyUSB0
include /BOARDS/ESP/Esp8266-Arduino-Makefile/espXArduino.mk
