# sudo apt install libdata-yaml-perl libyaml-perl

ARDUINO_VARIANT = nodemcu
INCLUDE_VARIANT = nodemcu
ARDUINO_ARCH=esp8266

SERIAL_PORT = /dev/ttyUSB0
SKETCH = esp_small_door.ino
BOARD = nodemcu
#CFLAGS += -I/BOARDS/ESP/Esp8266-Arduino-Makefile/esp8266-2.6.3/variants/generic/
#CXXFLAGS += -I/BOARDS/ESP/Esp8266-Arduino-Makefile/esp8266-2.6.3/variants/generic/

#CXXFLAGS += -I/BOARDS/ESP/Esp8266-Arduino-Makefile/esp32-1.0.4/variants/esp32
#CFLAGS += -I/BOARDS/ESP/Esp8266-Arduino-Makefile/esp32-1.0.4/variants/esp32

include /BOARDS/ESP/Esp8266-Arduino-Makefile/espXArduino.mk

