ARDUINO_VARIANT = esp8266 
ARDUINO_VARIANT = nodemcu
INCLUDE_VARIANT = esp8266
ARDUINO_ARCH = esp8266
BOARD = esp8266
# ARDUINO_VARIANT = nodemcu
SERIAL_PORT = /dev/ttyUSB0
SKETCH = ESPNOW.ino
SERIAL_PORT = /dev/ttyUSB0
# ESP8266_VERSION = 1.0.6
USER_DEFINES=ARDUINO_ARCH_ESP32
ARDUINO_ARCH = esp8266
#USR_SPECDIRS = ./libraries/ESPAsyncWebSrv/src

##########################################################################################
include /BOARDS/ESP/Esp8266-Arduino-Makefile/espXArduino.mk
